# The source package's name
SRC_NAME := tzdata
CREATE_SRC_DIR := 1

include description.mk
include ../common/basic.mk

# Rules for configuring and compiling the package
$(BUILD_DIR)/configured:
	> $@

$(BUILD_DIR)/built:
	> $@
